# -*- coding: utf-8 -*-
"""script_to_query.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AlNzwyAju61qeu71hPtXr3Lbq6vMqVm4
"""

import requests
import csv



#API Configuration:
API_URL = "https://api.collegefootballdata.com/teams/fbs"
API_KEY = "tt0RK/yEkrxHBpJt5Pc6I7QjdMjeqH8icksvlZ9pn2dznG+tZuF0HCbY5oaKtMRz"

#Function to query:
def get_team_data():
    try:
        headers = {
            'accept': 'application/json',
            'Authorization': f'Bearer {API_KEY}'
        }
        response = requests.get(API_URL, headers=headers, params={'team': 'Minnesota'})
        response.raise_for_status()
        return response.json()
    except requests.exceptions.RequestException as e:
        print(f"Error fetching data: {e}")
        return None



#Processing data and writing it to a CSV file:
def save_team_data_to_csv(filename='minnesota_team_data.csv'):
    fields = ['School', 'Mascot', 'Conference', 'Division']

    with open(filename, 'w', newline='') as csvfile:
        csvwriter = csv.writer(csvfile)
        csvwriter.writerow(fields)

        data = get_team_data()
        if data:
            for team in data:
                school = team.get('school', 'N/A')
                mascot = team.get('mascot', 'N/A')
                conference = team.get('conference', 'N/A')
                division = team.get('division', 'N/A')

                csvwriter.writerow([school, mascot, conference, division])
                print(f"Data for season {school} written to CSV file")
            else:
                print("No data to write.")

#Saving data to CSV file:
save_team_data_to_csv()

print("Minnesota team data saved to minnesota_team_data.csv.")